name: Run Make

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Print uname -m
        run: uname -m

      - name: Run make help
        run: make help

      - name: Run make
        run: make
